In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
a = np.ones((3, 4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
a = np.arange(0,10,1)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a.shape

(10,)

In [7]:
a.dtype


dtype('int64')

In [8]:
a = np.arange(0.1, 1.0, 0.1)
a.dtype

dtype('float64')

In [9]:
a = np.array([1, 2, 3], dtype=np.float64)
a.dtype

dtype('float64')

In [10]:
a[1]

np.float64(2.0)

In [11]:
a[0]

np.float64(1.0)

In [12]:
b = np.empty((3,3))
print(b)
b[1,1]

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]


np.float64(0.5)

In [13]:
b = np.empty((5))
b

array([4.67985490e-310, 0.00000000e+000, 4.67929596e-310, 4.67929583e-310,
       0.00000000e+000])

In [14]:
b[1:5]

array([0.00000000e+000, 4.67929596e-310, 4.67929583e-310, 0.00000000e+000])

In [15]:
b[4:5]

array([0.])

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a,b)    

[1 2 3] [4 5 6]


In [21]:
res = a + b
res

array([5, 7, 9])

In [22]:
res = a - b
res

array([-3, -3, -3])

In [24]:
res = a * 2
res

array([2, 4, 6])

In [26]:
res = a * b
res

array([ 4, 10, 18])

In [27]:
res = a ** 2
res

array([1, 4, 9])

In [ ]:
data = np.array([10, 20, 30, 40, 50])
np.mean(data) # или data.mean()

np.float64(30.0)

In [33]:
np.median(data)

np.float64(30.0)

In [34]:
print(np.min(data))
print(np.max(data))

10
50


In [35]:
np.sum(data)

np.int64(150)

In [36]:
np.var(data)

np.float64(200.0)

In [40]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.mean(data, axis=0))  # среднее по столбцам
print(np.mean(data, axis=1))  # среднее по строкам    


[4. 5. 6.]
[2. 5. 8.]
