In [3]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])  # создание массива NumPy
a

array([1, 2, 3])

In [ ]:
a = np.zeros((3, 4)) # создание массива из нулей размером 3x4
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a = np.ones((3, 4)) # создание массива из единиц размером 3x4
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a = np.arange(0,10,1) # создание массива с числами от 0 до 9 с шагом 1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.shape # получение формы массива

(10,)

In [ ]:
a.dtype # получение типа данных элементов массива

dtype('int64')

In [8]:
a = np.arange(0.1, 1.0, 0.1)
a.dtype

dtype('float64')

In [4]:
a = np.array([1, 2, 3], dtype=np.float64) # создание массива с указанием типа данных
a.dtype

dtype('float64')

In [5]:
print(a[1]) # доступ к элементу массива по индексу
print(a[0])

2.0
1.0


In [ ]:
b = np.empty((3,3)) 
print(b)
b[1,1] 

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]


np.float64(0.5)

In [ ]:
b = np.empty((5)) # создание массива элементами из памяти
b

array([4.67985490e-310, 0.00000000e+000, 4.67929596e-310, 4.67929583e-310,
       0.00000000e+000])

In [ ]:
b[1:5] # срез массива от индекса 1 до 4

array([0.00000000e+000, 4.67929596e-310, 4.67929583e-310, 0.00000000e+000])

In [ ]:
b[4:5] # срез массива от индекса 4 до 4

array([0.])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a,b)   

[1 2 3] [4 5 6]


In [ ]:
res = a + b # поэлементное сложение массивов
res

array([5, 7, 9])

In [ ]:
res = a - b # поэлементное вычитание массивов
res

array([-3, -3, -3])

In [ ]:
res = a * 2 # поэлементное умножение массива на число
res

array([2, 4, 6])

In [ ]:
res = a * b # поэлементное умножение массивов
res

array([ 4, 10, 18])

In [ ]:
res = a ** 2 # поэлементное возведение массива в степень
res

array([1, 4, 9])

In [ ]:
data = np.array([10, 20, 30, 40, 50])
np.mean(data) # вычисление среднего значения массива
# или data.mean()

np.float64(30.0)

In [ ]:
np.median(data) # вычисление медианы массива

np.float64(30.0)

In [ ]:
print(np.min(data)) # вычисление минимального значения массива
print(np.max(data)) # вычисление максимального значения массива

10
50


In [ ]:
np.sum(data) # вычисление суммы элементов массива

np.int64(150)

In [ ]:
np.var(data) # вычисление дисперсии элементов массива

np.float64(200.0)

In [40]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.mean(data, axis=0))  # среднее по столбцам
print(np.mean(data, axis=1))  # среднее по строкам    


[4. 5. 6.]
[2. 5. 8.]
