In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
a = np.ones((3, 4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
a = np.arange(0,10,1)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a.shape

(10,)

In [7]:
a.dtype


dtype('int64')

In [8]:
a = np.arange(0.1, 1.0, 0.1)
a.dtype

dtype('float64')

In [9]:
a = np.array([1, 2, 3], dtype=np.float64)
a.dtype

dtype('float64')

In [10]:
a[1]

np.float64(2.0)

In [11]:
a[0]

np.float64(1.0)

In [21]:
b = np.empty((3,3))
print(b)
b[1,1]

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]


np.float64(0.5)